version: '3.8'
services:
  maven:
    build:
      dockerfile: Dockerfile
      context: ./maven
    volumes:
      - type: volume
        source: ./war-files
        target: /app/boxfuse-sample-java-war-hello
  tomcat:
    image: tomcat:alpine
    volumes:
      - type: volume
        source: ./war-files
        target: /usr/local/tomcat/webapps/hello-1.0.war