version: '3'
services:
    maven:
        build:
            dockerfile: Dockerfile
            context: ./maven
        volumes:
            - type: bind
              source: ./war-files
              target: /app/boxfuse-sample-java-war-hello
    tomcat:
        image: tomcat:alpine
        volumes:
            - type: bind
              source: ./war-files
              target: /usr/local/tomcat/webapps/hello-1.0.war