version: '3.8'
services:
  maven:
    build:
      dockerfile: Dockerfile
      context: ./maven
    volumes:
      - war-files:/tmp
  tomcat:
    image: tomcat:alpine
    volumes:
      - war-files:/usr/local/tomcat/webapps/
    ports:
      - '8080:8080'
volumes:
  war-files: