version: '3.8'
services:
  maven:
    build:
      dockerfile: Dockerfile
      context: ./maven
    volumes:
      - war-files:/app/boxfuse-sample-java-war-hello/target
  tomcat:
    image: 'tomcat:alpim'
    volumes:
      - war-files:/usr/local/tomcat/webapps/
    ports:
      - '8080:8080'
volumes:
  war-files: